# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rules-python:
        patterns:
          - "rules_python*"
    # cooldown:
    #   default-days: 7

  - package-ecosystem: "pip" # TODO: consider "uv" instead
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
